/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * emergentBaselineFromSubstrate.ts
 *
 * v4.4 observation-only baselineActivity deriver.
 *
 * Instead of writing a time-driven sin oscillator into baselineActivity, this
 * function READS each cell's baselineActivity value from the local
 * conservation substrate's storageField. The downstream consumer
 * (updateBaselineAndResidue) still feeds baselineActivity into
 * currentBuffer, so when substrate cells are populated by the chain
 * (External → Medium → Membrane → Substrate), baselineActivity reflects
 * that local energy. When substrate is empty, baselineActivity is zero —
 * which is a valid observation per energy-realness principle 5
 * ("nothing happens" is also valid).
 *
 * No oscillation is generated by this function. Whether baselineActivity
 * varies over time depends entirely on the substrate dynamics
 * (localExchange / localDissipation / chain flow). v4.2 already proved the
 * substrate can produce non-trivial patterns under directional curvature.
 */

/**
 * Configuration knob for the emergent baseline deriver.
 */
export interface EmergentBaselineFromSubstrateConfig {
    /**
     * Linear scale applied when copying substrate.storageField[i] into
     * baselineActivity[i]. Default 1.0 — the substrate values pass through
     * unscaled. Use a smaller value (e.g. 0.01) to match the rough
     * amplitude range of the prior legacy oscillator if downstream
     * components expect small baselineActivity values.
     */
    substrateScale?: number;
    /**
     * Optional minimum value clamp. Default -Infinity (no clamp).
     */
    minValue?: number;
    /**
     * Optional maximum value clamp. Default +Infinity (no clamp).
     */
    maxValue?: number;
}

/**
 * Observation-only update of baselineActivity from substrate.storageField.
 *
 * Pre-conditions:
 * - `network.baselineActivity` is a typed array of length `network.numNodes`.
 * - `network.localConservationSubstrate.storageField` is a Float64Array of
 *   matching length when present.
 *
 * Post-conditions:
 * - When substrate is attached: baselineActivity[i] = clamp(scale * substrate.storageField[i]).
 * - When substrate is absent or size-mismatched: baselineActivity is filled
 *   with zeros (valid "nothing emerged" observation).
 *
 * Returns the substrate-availability state observed (useful for telemetry).
 */
export function deriveEmergentBaselineFromSubstrate(
    network: any,
    config: EmergentBaselineFromSubstrateConfig = {},
): {
    substrateAttached: boolean;
    sizeMismatch: boolean;
    totalAbsoluteBaseline: number;
} {
    const scale = Number.isFinite(config.substrateScale) ? (config.substrateScale as number) : 1.0;
    const minV = Number.isFinite(config.minValue) ? (config.minValue as number) : Number.NEGATIVE_INFINITY;
    const maxV = Number.isFinite(config.maxValue) ? (config.maxValue as number) : Number.POSITIVE_INFINITY;

    const target = network.baselineActivity;
    if (!target || typeof target.length !== 'number') {
        return { substrateAttached: false, sizeMismatch: false, totalAbsoluteBaseline: 0 };
    }
    const N = network.numNodes ?? target.length;

    const substrate = network.localConservationSubstrate;
    const storage = substrate?.storageField;
    const substrateAttached = !!storage && storage.length !== undefined;
    const sizeMismatch = substrateAttached && storage.length !== N;

    if (!substrateAttached || sizeMismatch) {
        // Nothing-emerged observation: substrate is absent or shape mismatch.
        // Fill with zeros — no time-driven oscillation is generated here.
        for (let i = 0; i < N; i++) target[i] = 0;
        return { substrateAttached, sizeMismatch, totalAbsoluteBaseline: 0 };
    }

    let totalAbs = 0;
    for (let i = 0; i < N; i++) {
        const raw = storage[i];
        const safe = Number.isFinite(raw) ? raw : 0;
        let value = safe * scale;
        if (value < minV) value = minV;
        if (value > maxV) value = maxV;
        target[i] = value;
        totalAbs += Math.abs(value);
    }
    return { substrateAttached: true, sizeMismatch: false, totalAbsoluteBaseline: totalAbs };
}
